---
title: "Untitled"
output: html_document
date: "2022-08-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
layers <- read_excel("comunas/layers.xlsx")
write.csv(layers, "comunas/layers.csv", row.names = FALSE)

#scenario_data <- read_excel("scenario_data.xlsx")
#write.csv(scenario_data, "comunas/conf/scenario_data_years.csv", row.names = FALSE)

```






Matriz
```{r}
library(readxl)
matriz <- read_excel("prep/_resilience/Matriz metas-resiliencias OHI Chile.xlsx",
                               sheet = "matriz")

write.csv(matriz, "comunas/conf/resilience_matrix.csv",
          row.names = F, na = "")

category <- read_excel("prep/_resilience/Matriz metas-resiliencias OHI Chile.xlsx",
                     sheet = "category")

write.csv(category, "comunas/conf/resilience_categories.csv",
          row.names = F, na = "")

```



```{r}
library(readxl)
matriz <- read_excel("prep/_pressures/matrizjunio2023presiones.xlsb.xlsx",
                               sheet = "matrizB")

write.csv(matriz, "comunas/conf/pressures_matrix.csv",
          row.names = F, na = "")

category <- read_excel("prep/_pressures/matrizjunio2023presiones.xlsb.xlsx",
                     sheet = "categoryB")

write.csv(category, "comunas/conf/pressure_categories.csv",
          row.names = F, na = "")

```

```{r}
goals <- read_excel("comunas/conf/goals.xlsx")

write.csv(goals, "comunas/conf/goals.csv", row.names = F, na = "")

```
















