---
title: "estado de las especies"
output: html_document
date: "2022-09-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readxl)
library(dplyr)
library(dplyr)

```


```{r}
estatus <- read_csv("prep/SPP/estatus.csv")

## Primer factor 
status <- data %>%
  dplyr::group_by(rgn_id, sp) %>%
  dplyr::summarize(suma = sum(IUCN_weight), n_sp =n()) 


h<- data %>% select(rgn_id, grid_id,  grid_area) 
h<-h[!duplicated(h), ]

status<- merge(status, h)

status <- status %>%
  dplyr::mutate(A = (1 - (suma/n_sp))) %>%
  dplyr::mutate(B = A * area_km2) %>%
  dplyr::group_by(rgn_id) %>%
  dplyr::summarize(A = sum(B))






##Segundo factor
h<- estatus %>% select(rgn_id, area_km2, id, area_km2) 
h<-h[!duplicated(h), ]

status2 <- h %>%
  dplyr::group_by(rgn_id) %>%
  dplyr::summarize(area_rgn = sum(area_km2)) 

status<- merge(status, status2, all.y = FALSE)

##Calculo del estado actual 
status_spp <- status %>%
  dplyr::mutate(score= (A / area_rgn)*100)    %>% 
     dplyr::mutate(
       year = 2021 ) %>% 
  dplyr::select(rgn_id, score)

##Calculo de la tendencia
trend_spp<- estatus %>% group_by(rgn_id) %>% 
  summarise(score = mean(IUCN_weight))

```


```{r}
area<- select(sp, rgn_id, area_km2)
area<- area[!duplicated(area), ]

sp

status <- sp %>%
  dplyr::mutate(A = (1 - (iucn_weight_sum/sp_count)),
                     B = A * grid_area)  %>%
  dplyr::group_by(rgn_id) %>%
  dplyr::summarize(A = sum(B)) %>%
  left_join(area, by = c("rgn_id")) %>%
  dplyr::mutate(score= (A / area_km2))    
  
```


```{r}
library(readxl)
sp <- read_excel("prep/SPP/grid_sp_rgn_chl_2021.xlsx")

status <- sp %>%
  dplyr::mutate(A = (iucn_weight_sum*grid_area),
                B = grid_area* sp_count)  %>%
  group_by(rgn_name) %>%
  summarise(rspp = c(sum(A))/ c(sum(B)))

xspp<-  status %>%
  mutate(status = pmax(c((rspp - 0.3)/0.70), 0))

write.table(xspp, "clipboard", sep="\t", row.names=F)

```





```{r}
sp<- merge(sp_grid, ESPECIES_MMA, 
           all.x = T)


status<- data.frame(IUCN= c("EX", "CR", "EN", "VU", "NT", "LC"),
                    cat = c(0,0.2,0.4,0.6,0.8,1))
sp<- merge(sp, status)

sp2<- sp%>%
  group_by(grid_id) %>%
  summarise(sum= sum(cat),
            n= n())

sp<- sp %>%
  select(grid_id, area_grid, rgn_id)

sp<- sp[!duplicated(sp), ]

sp3<- merge(sp2,sp)

status <- sp3 %>%
  dplyr::mutate(A = sum * area_grid,
                B = area_grid* n)  %>%
  group_by(rgn_id) %>%
  summarise(rspp = c(sum(A))/ c(sum(B)))

xspp<-  status %>%
  mutate(status = pmax(c((rspp - 0.3)/0.70), 0)*100)

write.table(xspp, "clipboard", sep="\t", row.names=F)
```


```{r}
trend<-  data.frame("trend"= c("Creciente", "Estable", "Decreciendo"),
                    cat = c(0.5, 0, -0.5))

sp<- merge(sp_grid, ESPECIES_MMA, all.x = T)

sp<- merge(sp, trend)


sp2<- sp %>%
  group_by(rgn_id) %>%
  summarise(trend= mean(cat))%>%
  mutate(dimension = "trend")

write.table(sp2, "clipboard", sep="\t", row.names=F)
```















